### ISSUE TITLE
Can you add description on this service?

### ISSUE THREAD

**Issue by elico** [jannson/smux_tunnel#1]
Can you add description on this service?
I couldn't understand what it was meant for and what it does.

**Comment by jannson** [comment]
sorry, response to you so laterly.
This is a test for myself, and It means:
1. smux is https://github.com/xtaci/smux ,  which can "MUltipleXing" one tcp connection to multiple net.Conn
2. By using smux, I can easy implement a tcp tunnel to local net , like what ssh tunnel does. But with this version, It can implement more easy.
3. At last, You can have a look at https://github.com/inconshreveable/ngrok
